const constants = {
  AUTH_LOGIN: 'AUTH_LOGIN',
  AUTH_LOGIN_SUCCESS: 'AUTH_LOGIN_SUCCESS',
  AUTH_LOGIN_FAILURE: 'AUTH_LOGIN_FAILURE',
  AUTH_LOGOUT: 'AUTH_LOGOUT',
  AUTH_LOGOUT_SUCCESS: 'AUTH_LOGOUT_SUCCESS',
  AUTH_LOGOUT_FAILURE: 'AUTH_LOGOUT_FAILURE',
  AUTH_REFRESH: 'AUTH_REFRESH',
  AUTH_REFRESH_SUCCESS: 'AUTH_REFRESH_SUCCESS',
  AUTH_REFRESH_FAILURE: 'AUTH_REFRESH_FAILURE',
} as const;

export default constants;
