
export default {
  AUTH_LOGIN: 'AUTH_LOGIN',
  AUTH_LOGIN_SUCCESS: 'AUTH_LOGIN_SUCCESS',
  AUTH_LOGIN_FAILURE: 'AUTH_LOGIN_FAILURE',
  AUTH_REFRESH: 'AUTH_REFRESH',
  AUTH_REFRESH_SUCCESS: 'AUTH_REFRESH_SUCCESS',
  AUTH_REFRESH_FAILURE: 'AUTH_REFRESH_FAILURE',
} as const;