[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Content-Type = "application/json"
    Access-Control-Allow-Credentials = "true"
    Access-Control-Allow-Headers = "Authorization, Content-Type"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200