
export default {
  HOURS_CREATE: 'HOURS_CREATE',
  HOURS_CREATE_SUCCESS: 'HOURS_CREATE_SUCCESS',
  HOURS_CREATE_FAILURE: 'HOURS_CREATE_FAILURE',
  HOURS_READ: 'HOURS_READ',
  HOURS_READ_SUCCESS: 'HOURS_READ_SUCCESS',
  HOURS_READ_FAILURE: 'HOURS_READ_FAILURE',
  HOURS_UPDATE: 'HOURS_UPDATE',
  HOURS_UPDATE_SUCCESS: 'HOURS_UPDATE_SUCCESS',
  HOURS_UPDATE_FAILURE: 'HOURS_UPDATE_FAILURE',
  HOURS_DELETE: 'HOURS_DELETE',
  HOURS_DELETE_SUCCESS: 'HOURS_DELETE_SUCCESS',
  HOURS_DELETE_FAILURE: 'HOURS_DELETE_FAILURE',
} as const;